CREATE USER airflow WITH PASSWORD 'airflow';
CREATE USER hive WITH PASSWORD 'hive';
CREATE USER main WITH PASSWORD 'main';

CREATE DATABASE airflow OWNER airflow;
CREATE DATABASE hive OWNER hive;
CREATE DATABASE data_warehouse OWNER main;

GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow;
GRANT ALL PRIVILEGES ON DATABASE hive TO hive;
GRANT ALL PRIVILEGES ON DATABASE data_warehouse TO main;